apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <body>

    <h1> ZADANIE 2 LAB 10 </h1>
    <p> 
    Image: 
    28ludmila/zad2:1.1.0
    </p>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: zad2-cm
